title: Salazar26617306
logo: /assets/img/logo.png
description: I am an avid writer tracking latest crypto & tech trends. Focused on futuristic stuff, AR, VR, CG and innovations at intersection of finance, lifestyle & emerging tech.<br>12345123451234512345<a href="/posts.html">Posts</a>
#<br><br>Quick links: <a href="/posts.html">Posts</a> / <a href="./">Top</a>
show_downloads: false
twitter_username: Salazar26617306
theme: jekyll-theme-minimal
# https://github.com/pages-themes/minimal
##theme: jekyll-theme-leap-day
#
## Here are instructions for the modernist theme:
## https://github.com/pages-themes/modernist
## remote_theme: pages-themes/modernist@v0.2.0
#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
