title: Salazar26617306
logo: /assets/img/logo.png
description: I am an avid writer tracking latest crypto & tech trends. Focused on futuristic stuff, AR, VR, CG and innovations at intersection of finance, lifestyle & emerging tech.<br><p>Quick links to my <a href="/microblog.html">Micro-blog</a> | <a href="/posts.html">Posts</a> | <a href="/">Top</a></p>
show_downloads: false
twitter_username: Salazar26617306
theme: jekyll-theme-minimal
# https://github.com/pages-themes/minimal
#
# Check out
#  https://chadbaldwin.net/2021/03/14/how-to-build-a-sql-blog.html
#  https://github.com/chadbaldwin/simple-blog-bootstrap/generate
#  https://dfederm.com/
#  https://lukasrosenstock.net/ ; https://github.com/LukasRos/microblog-mirror/tree/master
#
##theme: jekyll-theme-leap-day
#
## Here are instructions for the modernist theme:
## https://github.com/pages-themes/modernist
## remote_theme: pages-themes/modernist@v0.2.0
#remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - _plugins/twitter_hashtag_filter.rb
#- jekyll-remote-theme # add this line to the plugins list if you already have one
